---
# tasks file for bvansomeren.docker

- name: ensure python setup tools
  yum: name=python-setuptools state=present

- name: ensure backports.ssl_match_hostname for docker-py
  pip: name=backports.ssl_match_hostname state=present
  
- name: ensure docker-py for Ansible
  pip: name=docker-py state=present

- name: ensure docker repo is added
  template: src=docker.repo dest=/etc/yum.repos.d/docker.repo
  when: docker_userepo

- name: ensure docker-engine is installed
  package: name=docker-engine state=present
  when: docker_userepo

- name: ensure docker is installed
  package: name=docker state=present
  when: not docker_userepo  

- name: ensure the docker service is started by default
  service: name=docker state=started enabled=yes
